In [4]:
import pandas as pd

df = pd.read_csv('owid-energy-data.csv')

df_asia = df[df['country'] == 'Asia']

df_asia.tail()

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
1323,Asia,2019,NaN,4.627739e+09,NaN,26.987,34.605,35.186,162.833,48.324,...,2.748,1.225,10.339,122.620,1357.211,111.059,513.95,293.277,3.600,1.608
1324,Asia,2020,NaN,4.663087e+09,NaN,5.907,9.619,36.982,172.452,53.801,...,3.238,1.471,12.408,162.800,1520.011,124.021,578.32,325.967,3.991,1.809
1325,Asia,2021,NaN,4.693332e+09,NaN,8.219,14.173,39.764,186.625,62.572,...,3.798,1.738,36.230,543.123,2063.134,167.352,785.44,439.588,5.036,2.335
1326,Asia,2022,NaN,4.721383e+09,NaN,10.889,20.322,43.832,206.948,69.393,...,4.572,2.200,15.328,307.552,2370.686,191.817,905.64,502.117,5.585,2.706
1327,Asia,2023,NaN,4.751820e+09,NaN,14.130,29.243,49.705,236.190,NaN,...,NaN,2.664,15.656,361.202,2731.887,NaN,NaN,574.914,NaN,2.988

In [5]:
df_asia.describe()

,year,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,biofuel_electricity,biofuel_share_elec,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
count,124.000000,1.240000e+02,0.0,23.000000,58.000000,59.000000,59.000000,23.000000,23.000000,23.000000,...,38.000000,59.000000,33.000000,58.000000,59.000000,58.000000,58.000000,59.000000,38.000000,59.000000
mean,1961.500000,2.260274e+09,NaN,34.388304,4.072276,6.796949,30.885644,26.046739,116.021739,1.015565,...,0.566211,0.210271,41.809030,47.101500,275.432678,19.190276,87.649328,59.947492,1.005789,0.337729
std,35.939764,1.246299e+09,NaN,43.683719,9.103374,12.666836,59.006653,18.488391,89.308717,0.449415,...,1.176424,0.556487,47.293175,102.219279,611.065252,42.531842,198.191062,130.312529,1.547806,0.702587
min,1900.000000,9.310214e+08,NaN,-16.046000,-14.861000,0.000000,0.000000,7.373000,27.540000,0.566000,...,0.000000,0.000000,-12.355000,-0.407000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1930.750000,1.169587e+09,NaN,12.637000,0.000000,0.000000,0.000000,11.161500,44.690000,0.640000,...,0.001000,0.000000,17.385000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018000,0.000000
50%,1961.500000,1.742969e+09,NaN,25.309000,0.000000,0.000000,0.000000,20.094000,85.770000,0.864000,...,0.020000,0.000000,30.850000,0.468500,1.709000,0.130000,0.444000,0.498000,0.105000,0.006000
75%,1992.250000,3.337842e+09,NaN,41.952500,4.740250,7.844500,32.545000,34.977000,157.610000,1.267000,...,0.236000,0.017000,52.936000,45.230000,116.596000,7.231250,29.750000,28.081500,1.607750,0.195000
max,2023.000000,4.751820e+09,NaN,199.155000,34.605000,49.705000,236.190000,69.393000,327.630000,2.020000,...,4.572000,2.664000,269.115000,543.123000,2731.887000,191.817000,905.640000,574.914000,5.585000,2.988000